# Pre work
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm




# --- GENERAL SETTINGS ---
set -g mouse on               # Enable mouse clicking, resizing, and scrolling
set -g base-index 1           # Start windows at 1 instead of 0
setw -g pane-base-index 1     # Start panes at 1 instead of 0
set -g renumber-windows on    # Automatically renumber windows when one is closed
setw -g mode-keys vi # Use vi keys in copy mode and menus

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"

# --- KEYBINDS ---
# Remap prefix to Ctrl+a (easier to reach)
# unbind C-b
# set -g prefix C-a
# bind C-a send-prefix

# Split panes using | and - (more intuitive)
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Switch panes using Alt + Arrow keys (No prefix needed!)
# bind -n M-Left select-pane -L
# bind -n M-Right select-pane -R
# bind -n M-Up select-pane -U
# bind -n M-Down select-pane -D

# pane movement shortcuts (same as vim)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Fast config reload
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# --- PLUGINS ---
# To install: Prefix + I
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Persistence (Save/Restore sessions)
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Theme / Visuals
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'powerline/default/cyan'

# Initialize TPM (Keep this at the very bottom)
run '~/.tmux/plugins/tpm/tpm'